Repository grasshopper47/NFTOpt, pull requests merged in 2022-05, with the labels that each got.

#74 refactor
  src/components/OptionDetailsPreview.tsx
  src/components/OptionListItemPreview.tsx
  src/pages/_app.tsx
  src/pages/create-option.tsx
  src/pages/explore-options.tsx
  src/pages/my-options.tsx
  src/utils/NFT/localhost.ts
  src/utils/NFT/opensea.ts
  src/utils/backend.ts
  src/utils/dummyData.ts
  src/utils/frontend.ts
  src/utils/metamask.ts
  src/utils/options.ts
  src/utils/types.ts
Labels: enhancement, CRITICAL

#83 Add nonce to transaction options whenever it gets sent
  addresses.json
  readme.md
  src/components/OptionDetailsPreview.tsx
  src/pages/create-option.tsx
  src/utils/NFT/localhost.ts
  src/utils/frontend.ts
  src/utils/metamask.ts
Labels: improvement, important

#85 add addresses.json to gitignore
  .gitignore
Labels: duplicate

#81 exercise option fails
  scripts/deploy.ts
  src/components/OptionDetailsPreview.tsx
  src/pages/create-option.tsx
  src/utils/backend.ts
Labels: CRITICAL
